apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment200
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp200
  template:
    metadata:
      labels:
        app: myapp200
    spec:
      containers:
      - name: myapp-container200
        image: "ranatarek/pipline_docker_image200:latest"
        ports:
        - containerPort: 8000